# Docker Image which is used as foundation to create
# a custom Docker Image with this Dockerfile
FROM arm64v8/node:12.18-alpine as react-build

# Add Maintainer Info
LABEL maintainer="LitmusChaos"

# Stage 2: the production environment
FROM nginxinc/nginx-unprivileged:1.18-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY  build/ /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
