name: build-arch-pipeline
on:
  push:
    branches:
      - master
      - ^v[0-9]*.[0-9]*.x$
    tags:
      - "*"

jobs:
  docker-build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          file: litmus-portal/frontend/Dockerfile
          platforms: linux/arm64
          tags: jonsy13/frontend:ci
