name: Portal-E2E K3S Pipeline
on:
  workflow_dispatch:
    inputs:
      Tag:
        default: "ci"
      Module:
        default: "All"

# All Environments variables declared and set here.
env:
  SELF_AGENT: "self-agent"
  EXTERNAL_AGENT: "external-agent"

# Jobs for deploying and testing litmus-portal on a KinD Cluster
jobs:
  Cluster-Scope-Mode:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: AbsaOSS/k3d-action@v1.5.0
        name: Create 1st Cluster
        with:
          cluster-name: ${{ env.SELF_AGENT }}
          args: --agents 1

      - run: |
          kubectl create ns clc-staging
          NS=$(eval "kubectl get ns | awk 'clc-staging'")
          if [[ -z "$NS" ]];then
            kubectl create ns clc-staging
          else
              echo "clc-staging namespace found ✓"
          fi
