name: Litmus-CI
on:
  issue_comment:
    types: [created]
    branches:
      - master

jobs:
  tests:
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/run-e2e')
    runs-on: ubuntu-20.04
    steps:
      - name: Creating KIND Cluster
        run: kind create cluster --name k1

      - name: Testing
        run: |
          kubectl wait node --all --for condition=ready --timeout=90s
          kubectl cluster-info --context kind-k1
          kubectl get nodes
          kubectl get pods -n kube-system

      - name: Deploying Portal
        run: kubectl apply -f https://raw.githubusercontent.com/litmuschaos/litmus/master/litmus-portal/cluster-k8s-manifest.yml
