name: Release
on:
  create:
    tags:
      - "**"

defaults:
  run:
    working-directory: litmus-portal
    shell: bash

env:
  GRAPHQL_SERVER_IMAGE: "litmusportal-server"
  AUTHENTICATION_SERVER_IMAGE: "litmusportal-auth-server"
  FRONTEND_IMAGE: "litmusportal-frontend"
  SUBSCRIBER_IMAGE: "litmusportal-subscriber"
  EVENT_TRACKER: "litmusportal-event-tracker"
  UPGRADE_AGENT_CP: "upgrade-agent-cp"

jobs:
  get-envs:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_TAG: ${{ steps.envs.outputs.RELEASE_TAG }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: envs
        run: |
          TAG="${GITHUB_REF#refs/*/}"
          echo "::set-output name=RELEASE_TAG::$TAG"

  docker-build-and-push-graphql-server:
    runs-on: ubuntu-latest
    needs:
      - get-envs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          RELEASE_TAG: ${{ needs.get-envs.outputs.RELEASE_TAG }}
        with:
          push: true
          file: ./litmus-portal/graphql-server/Dockerfile
          context: ./litmus-portal/graphql-server
          platforms: ${{ secrets.PLATFORMS }}
          tags: ${{ secrets.REPONAME }}/${{ env.GRAPHQL_SERVER_IMAGE }}:${{ env.RELEASE_TAG }}

  docker-build-and-push-authentication-server:
    runs-on: ubuntu-latest
    needs:
      - get-envs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          RELEASE_TAG: ${{ needs.get-envs.outputs.RELEASE_TAG }}
        with:
          push: true
          file: ./litmus-portal/authentication/Dockerfile
          context: ./litmus-portal/authentication
          platforms: ${{ secrets.PLATFORMS }}
          tags: ${{ secrets.REPONAME }}/${{ env.AUTHENTICATION_SERVER_IMAGE }}:${{ env.RELEASE_TAG }}

  docker-build-and-push-subscriber:
    runs-on: ubuntu-latest
    needs:
      - get-envs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          RELEASE_TAG: ${{ needs.get-envs.outputs.RELEASE_TAG }}
        with:
          push: true
          file: ./litmus-portal/cluster-agents/subscriber/Dockerfile
          context: ./litmus-portal/cluster-agents/subscriber
          platforms: ${{ secrets.PLATFORMS }}
          tags: ${{ secrets.REPONAME }}/${{ env.SUBSCRIBER_IMAGE }}:${{ env.RELEASE_TAG }}

  docker-build-and-push-event-tracker:
    runs-on: ubuntu-latest
    needs:
      - get-envs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          RELEASE_TAG: ${{ needs.get-envs.outputs.RELEASE_TAG }}
        with:
          push: true
          file: ./litmus-portal/cluster-agents/event-tracker/Dockerfile
          context: ./litmus-portal/cluster-agents/event-tracker
          platforms: ${{ secrets.PLATFORMS }}
          tags: ${{ secrets.REPONAME }}/${{ env.EVENT_TRACKER }}:${{ env.RELEASE_TAG }}

  docker-build-and-push-upgrade-agent-cp:
    runs-on: ubuntu-latest
    needs:
      - get-envs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          RELEASE_TAG: ${{ needs.get-envs.outputs.RELEASE_TAG }}
        with:
          push: true
          file: ./litmus-portal/upgrade-agents/control-plane/Dockerfile
          context: ./litmus-portal/upgrade-agents/control-plane
          platforms: ${{ secrets.PLATFORMS }}
          tags: ${{ secrets.REPONAME }}/${{ env.UPGRADE_AGENT_CP }}:${{ env.RELEASE_TAG }}
