name: s3-bucket-sync

on:
  push:
    branches:
      - master
      - staging

defaults:
  run:
    working-directory: "litmus-portal"

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      public: ${{ steps.filter.outputs.public }}

    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            public:
              - 'litmus-portal/frontend/public/**'

  build:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.public == 'true'
    defaults:
      run:
        shell: bash
        working-directory: litmus-portal/frontend/public
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}

      - name: Copy files to the s3 bucket
        run: |
          aws s3 sync avatars s3://${{ secrets.AWS_S3_BUCKET_NAME }}/avatars
          aws s3 sync icons s3://${{ secrets.AWS_S3_BUCKET_NAME }}/icons
          aws s3 cp index.html s3://${{ secrets.AWS_S3_BUCKET_NAME }}/ 
          aws s3 cp index.css s3://${{ secrets.AWS_S3_BUCKET_NAME }}/files/
          aws s3 cp favicon.ico s3://${{ secrets.AWS_S3_BUCKET_NAME }}/files/
          aws s3 cp locales/en/translation.yaml s3://${{ secrets.AWS_S3_BUCKET_NAME }}/files/
